import 'main/index.scss';


export function vt() {
    return [
        'table',
        ['tr', ['th', "Field"], ['th', "Value(s)"], ['th', "Last update"]],
        ['tr', ['td', '0:0'], ['td', `${r.get('remote', 'adapter', '0:0')}`], ['td', `${r.get('remote', 'adapter', '0:0-timestamp')}`]],
        ['tr', ['td', '0:1'], ['td', `${r.get('remote', 'adapter', '0:1')}`], ['td', `${r.get('remote', 'adapter', '0:1-timestamp')}`]],
        ['tr', ['td', '1:0'], ['td', `${r.get('remote', 'adapter', '1:0')}`], ['td', `${r.get('remote', 'adapter', '1:0-timestamp')}`]],
        ['tr', ['td', '1:1'], ['td', `${r.get('remote', 'adapter', '1:1')}`], ['td', `${r.get('remote', 'adapter', '1:1-timestamp')}`]],
        ['tr', ['td', '2:0'], ['td', `${r.get('remote', 'adapter', '2:0')}`], ['td', `${r.get('remote', 'adapter', '2:0-timestamp')}`]],
        ['tr', ['td', '2:1'], ['td', `${r.get('remote', 'adapter', '2:1')}`], ['td', `${r.get('remote', 'adapter', '2:1-timestamp')}`]],
        ['tr', ['td', '3:0'], ['td', `${r.get('remote', 'adapter', '3:0')}`], ['td', `${r.get('remote', 'adapter', '3:0-timestamp')}`]],
        ['tr', ['td', '3:1'], ['td', `${r.get('remote', 'adapter', '3:1')}`], ['td', `${r.get('remote', 'adapter', '3:1-timestamp')}`]],
        ['tr', ['td', '4:0'], ['td', `${r.get('remote', 'adapter', '4:0')}`], ['td', `${r.get('remote', 'adapter', '4:0-timestamp')}`]],
        ['tr', ['td', '4:1'], ['td', `${r.get('remote', 'adapter', '4:1')}`], ['td', `${r.get('remote', 'adapter', '4:1-timestamp')}`]],
        ['tr', ['td', '5:0'], ['td', `${r.get('remote', 'adapter', '5:0')}`], ['td', `${r.get('remote', 'adapter', '5:0-timestamp')}`]],
        ['tr', ['td', '5:1'], ['td', `${r.get('remote', 'adapter', '5:1')}`], ['td', `${r.get('remote', 'adapter', '5:1-timestamp')}`]],
        ['tr', ['td', '6:0'], ['td', `${r.get('remote', 'adapter', '6:0')}`], ['td', `${r.get('remote', 'adapter', '6:0-timestamp')}`]],
        ['tr', ['td', '6:1'], ['td', `${r.get('remote', 'adapter', '6:1')}`], ['td', `${r.get('remote', 'adapter', '6:1-timestamp')}`]],
        ['tr', ['td', '10:0'], ['td', `${r.get('remote', 'adapter', '10:0')}`], ['td', `${r.get('remote', 'adapter', '10:0-timestamp')}`]],
        ['tr', ['td', '10:1'], ['td', `${r.get('remote', 'adapter', '10:1')}`], ['td', `${r.get('remote', 'adapter', '10:1-timestamp')}`]],
        ['tr', ['td', '10:2'], ['td', `${r.get('remote', 'adapter', '10:2')}`], ['td', `${r.get('remote', 'adapter', '10:2-timestamp')}`]],
        ['tr', ['td', '10:3'], ['td', `${r.get('remote', 'adapter', '10:3')}`], ['td', `${r.get('remote', 'adapter', '10:3-timestamp')}`]],
        ['tr', ['td', '10:4'], ['td', `${r.get('remote', 'adapter', '10:4')}`], ['td', `${r.get('remote', 'adapter', '10:4-timestamp')}`]],
        ['tr', ['td', '11:0'], ['td', `${r.get('remote', 'adapter', '11:0')}`], ['td', `${r.get('remote', 'adapter', '11:0-timestamp')}`]],
        ['tr', ['td', '11:1'], ['td', `${r.get('remote', 'adapter', '11:1')}`], ['td', `${r.get('remote', 'adapter', '11:1-timestamp')}`]],
        ['tr', ['td', '11:2'], ['td', `${r.get('remote', 'adapter', '11:2')}`], ['td', `${r.get('remote', 'adapter', '11:2-timestamp')}`]],
        ['tr', ['td', '11:3'], ['td', `${r.get('remote', 'adapter', '11:3')}`], ['td', `${r.get('remote', 'adapter', '11:3-timestamp')}`]],
        ['tr', ['td', '11:4'], ['td', `${r.get('remote', 'adapter', '11:4')}`], ['td', `${r.get('remote', 'adapter', '11:4-timestamp')}`]],
        ['tr', ['td', '12:0'], ['td', `${r.get('remote', 'adapter', '12:0')}`], ['td', `${r.get('remote', 'adapter', '12:0-timestamp')}`]],
        ['tr', ['td', '12:1'], ['td', `${r.get('remote', 'adapter', '12:1')}`], ['td', `${r.get('remote', 'adapter', '12:1-timestamp')}`]],
        ['tr', ['td', '12:2'], ['td', `${r.get('remote', 'adapter', '12:2')}`], ['td', `${r.get('remote', 'adapter', '12:2-timestamp')}`]],
        ['tr', ['td', '12:3'], ['td', `${r.get('remote', 'adapter', '12:3')}`], ['td', `${r.get('remote', 'adapter', '12:3-timestamp')}`]],
        ['tr', ['td', '12:4'], ['td', `${r.get('remote', 'adapter', '12:4')}`], ['td', `${r.get('remote', 'adapter', '12:4-timestamp')}`]],
        ['tr', ['td', '13:0'], ['td', `${r.get('remote', 'adapter', '13:0')}`], ['td', `${r.get('remote', 'adapter', '13:0-timestamp')}`]],
        ['tr', ['td', '13:1'], ['td', `${r.get('remote', 'adapter', '13:1')}`], ['td', `${r.get('remote', 'adapter', '13:1-timestamp')}`]],
        ['tr', ['td', '13:2'], ['td', `${r.get('remote', 'adapter', '13:2')}`], ['td', `${r.get('remote', 'adapter', '13:2-timestamp')}`]],
        ['tr', ['td', '13:3'], ['td', `${r.get('remote', 'adapter', '13:3')}`], ['td', `${r.get('remote', 'adapter', '13:3-timestamp')}`]],
        ['tr', ['td', '13:4'], ['td', `${r.get('remote', 'adapter', '13:4')}`], ['td', `${r.get('remote', 'adapter', '13:4-timestamp')}`]],
        ['tr', ['td', '20:0'], ['td', `${r.get('remote', 'adapter', '20:0')}`], ['td', `${r.get('remote', 'adapter', '20:0-timestamp')}`]],
        ['tr', ['td', '20:1'], ['td', `${r.get('remote', 'adapter', '20:1')}`], ['td', `${r.get('remote', 'adapter', '20:1-timestamp')}`]],
        ['tr', ['td', '20:2'], ['td', `${r.get('remote', 'adapter', '20:2')}`], ['td', `${r.get('remote', 'adapter', '20:2-timestamp')}`]],
        ['tr', ['td', '20:3'], ['td', `${r.get('remote', 'adapter', '20:3')}`], ['td', `${r.get('remote', 'adapter', '20:3-timestamp')}`]],
        ['tr', ['td', '20:4'], ['td', `${r.get('remote', 'adapter', '20:4')}`], ['td', `${r.get('remote', 'adapter', '20:4-timestamp')}`]],
        ['tr', ['td', '30:0'], ['td', `${r.get('remote', 'adapter', '30:0')}`], ['td', `${r.get('remote', 'adapter', '30:0-timestamp')}`]],
        ['tr', ['td', '30:1'], ['td', `${r.get('remote', 'adapter', '30:1')}`], ['td', `${r.get('remote', 'adapter', '30:1-timestamp')}`]],
        ['tr', ['td', '30:2'], ['td', `${r.get('remote', 'adapter', '30:2')}`], ['td', `${r.get('remote', 'adapter', '30:2-timestamp')}`]],
        ['tr', ['td', '30:3'], ['td', `${r.get('remote', 'adapter', '30:3')}`], ['td', `${r.get('remote', 'adapter', '30:3-timestamp')}`]],
        ['tr', ['td', '30:4'], ['td', `${r.get('remote', 'adapter', '30:4')}`], ['td', `${r.get('remote', 'adapter', '30:4-timestamp')}`]],
        ['tr', ['td', '30:5'], ['td', `${r.get('remote', 'adapter', '30:5')}`], ['td', `${r.get('remote', 'adapter', '30:5-timestamp')}`]],
        ['tr', ['td', '30:6'], ['td', `${r.get('remote', 'adapter', '30:6')}`], ['td', `${r.get('remote', 'adapter', '30:6-timestamp')}`]],
        ['tr', ['td', '30:7'], ['td', `${r.get('remote', 'adapter', '30:7')}`], ['td', `${r.get('remote', 'adapter', '30:7-timestamp')}`]],
        ['tr', ['th', "Field"], ['th', "Value(s)"], ['th', "Last update"]]
    ];
}
